# Dependencies
markdown:            kramdown
highlighter:         rouge
gems: [jekyll-paginate, jekyll-gist, jemoji]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               shansky
tagline:             'shansky blog'
description:         'Shansky blog page written in "pinglish" (not english, not even polish) powered on <a href="http://jekyllrb.com" target="_blank">Jekyll</a> and based on Lanyon theme made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://blog.shansky.pl
baseurl:             /
paginate:            5
timezone:            Europe/Warsaw

# About/contact
author:
  name:              Shansky
  url:               https://twitter.com/shansky
  email:             mail@not.ready

# Custom vars
version:             1.0.0

# Custom pages
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'